services:
  - type: web
    name: ringba-rpc-monitor
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    healthCheckPath: /
    # Render creates an internal health check endpoint behind the scenes,
    # so we don't worry about it failing for our script
    scaling:
      minInstances: 1
      maxInstances: 1
    envVars:
      - key: RINGBA_EMAIL
        sync: false
      - key: RINGBA_PASSWORD
        sync: false
      - key: SLACK_WEBHOOK_URL
        sync: false 